yellow:

  A:
    ip: "127.0.0.1"
    port: 12345
    grSimID : 0
    shellID : 1
    has_chip_kick: false

  B:
    ip: "127.0.0.1"
    port: 50514
    grSimID : 1
    shellID : 2
    has_chip_kick: false

  C:
    ip: "127.0.0.1"
    port: 50514
    grSimID : 2
    shellID : 3
    has_chip_kick: false

  D:
    ip: "127.0.0.1"
    port: 50514
    grSimID : 3
    shellID : 4 
    has_chip_kick: false

  E: 
    ip: "127.0.0.1"
    port: 50514
    grSimID : 4
    shellID : 5
    has_chip_kick: false

  F:
    ip: "127.0.0.1"
    port: 50514
    grSimID : 5
    shellID : 6
    has_chip_kick: false


blue:

  A:
    ip: "127.0.0.1"
    port: 12345
    grSimID : 0
    shellID : 1
    has_chip_kick: false

  B:
    ip: "127.0.0.1"
    port: 50514
    grSimID : 1
    shellID : 2
    has_chip_kick: false

  C:
    ip: "127.0.0.1"
    port: 50514
    grSimID : 2
    shellID : 3
    has_chip_kick: false

  D:
    ip: "127.0.0.1"
    port: 50514
    grSimID : 3
    shellID : 4 
    has_chip_kick: false

  E: 
    ip: "127.0.0.1"
    port: 50514
    grSimID : 4
    shellID : 5
    has_chip_kick: false

  F:
    ip: "127.0.0.1"
    port: 50514
    grSimID : 5
    shellID : 6
    has_chip_kick: false

grSim:
  ip: "127.0.0.1"
  port: 20010

vision:
  multicast-group: "224.5.23.2"
  port: 10006

gc:
  multicast-group: '224.5.23.1'
  port: 10003 