import logging
import enum
from enum import auto, unique
from typing import Optional, Union, List


class Command(enum.Enum):
    HALT = 0
    STOP = 1
    NORMAL_START = 2
    FORCE_START = 3
    PREPARE_KICKOFF_YELLOW = 4
    PREPARE_KICKOFF_BLUE = 5
    PREPARE_PENALTY_YELLOW = 6
    PREPARE_PENALTY_BLUE = 7
    DIRECT_FREE_YELLOW = 8
    DIRECT_FREE_BLUE = 9
    INDIRECT_FREE_YELLOW = 10
    INDIRECT_FREE_BLUE = 11
    TIMEOUT_YELLOW = 12
    TIMEOUT_BLUE = 13
    GOAL_YELLOW = 14
    GOAL_BLUE = 15
    BALL_PLACEMENT_YELLOW = 16
    BALL_PLACEMENT_BLUE = 17

class Team(enum.Enum):
    BLUE = 0
    YELLOW = 1
    
class GameEventType(enum.Enum):
    UNKNOWN_GAME_EVENT_TYPE = 0

    BALL_LEFT_FIELD_TOUCH_LINE = 6
    BALL_LEFT_FIELD_GOAL_LINE = 7
    AIMLESS_KICK = 11

    ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA = 19
    DEFENDER_IN_DEFENSE_AREA = 31
    BOUNDARY_CROSSING = 41
    KEEPER_HELD_BALL = 13
    BOT_DRIBBLED_BALL_TOO_FAR = 17

    BOT_PUSHED_BOT = 24
    BOT_HELD_BALL_DELIBERATELY = 26
    BOT_TIPPED_OVER = 27
    BOT_DROPPED_PARTS = 47

    ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA = 15
    BOT_KICKED_BALL_TOO_FAST = 18
    BOT_CRASH_UNIQUE = 22
    BOT_CRASH_DRAWN = 21

    DEFENDER_TOO_CLOSE_TO_KICK_POINT = 29
    BOT_TOO_FAST_IN_STOP = 28
    BOT_INTERFERED_PLACEMENT = 20
    EXCESSIVE_BOT_SUBSTITUTION = 48

    POSSIBLE_GOAL = 39
    GOAL = 8
    INVALID_GOAL = 42

    ATTACKER_DOUBLE_TOUCHED_BALL = 14
    PLACEMENT_SUCCEEDED = 5
    PENALTY_KICK_FAILED = 43

    NO_PROGRESS_IN_GAME = 2
    PLACEMENT_FAILED = 3
    MULTIPLE_CARDS = 32
    MULTIPLE_FOULS = 34
    BOT_SUBSTITUTION = 37
    TOO_MANY_ROBOTS = 38
    CHALLENGE_FLAG = 44
    CHALLENGE_FLAG_HANDLED = 46
    EMERGENCY_STOP = 45

    UNSPORTING_BEHAVIOR_MINOR = 35
    UNSPORTING_BEHAVIOR_MAJOR = 36

class Stage(enum.IntEnum):
    NORMAL_FIRST_HALF_PRE = 0
    NORMAL_FIRST_HALF = 1
    NORMAL_HALF_TIME = 2
    NORMAL_SECOND_HALF_PRE = 3
    NORMAL_SECOND_HALF = 4
    EXTRA_TIME_BREAK = 5
    EXTRA_FIRST_HALF_PRE = 6
    EXTRA_FIRST_HALF = 7
    EXTRA_HALF_TIME = 8
    EXTRA_SECOND_HALF_PRE = 9
    EXTRA_SECOND_HALF = 10
    PENALTY_SHOOTOUT_BREAK = 11
    PENALTY_SHOOTOUT = 12
    POST_GAME = 13

class MatchType(enum.Enum):
    UNKNOWN_MATCH = 0
    GROUP_PHASE = 1
    ELIMINATION_PHASE = 2
    FRIENDLY = 3