1:
  isYellow: true
  baseID: "A"
  ip: "127.0.0.1"
  port: 12345
  shellID: 1
  has_chip_kick: 

2:
  isYellow: false 
  baseID: "B"
  ip: "127.0.0.1"
  port: 50514
  shellID: 2
  has_chip_kick: 

3:
  isYellow: 
  baseID: "C"
  ip: "127.0.0.1"
  port: 50514
  shellID: 3
  has_chip_kick: 

4:
  isYellow: 
  baseID: "D"
  ip: "127.0.0.1"
  port: 50514
  shellID: 4 
  has_chip_kick: 

5: 
  isYellow: 
  baseID: "E"
  ip: "127.0.0.1"
  port: 50514
  shellID: 5
  has_chip_kick: 

6:
  isYellow: 
  baseID: "F"
  ip: "127.0.0.1"
  port: 50514
  shellID: 6
  has_chip_kick: 