yellow:

  0:
    ip: "127.0.0.1"
    port: 12345
    shellID: 1
    has_chip_kick: false

  1:
    ip: "127.0.0.1"
    port: 50514
    shellID: 2
    has_chip_kick: false

  2:
    ip: "127.0.0.1"
    port: 50514
    shellID: 3
    has_chip_kick: false

  3:
    ip: "127.0.0.1"
    port: 50514
    shellID: 4 
    has_chip_kick: false

  4: 
    ip: "127.0.0.1"
    port: 50514
    shellID: 5
    has_chip_kick: false

  5:
    ip: "127.0.0.1"
    port: 50514
    shellID: 6
    has_chip_kick: false


blue:

  0:
    ip: "127.0.0.1"
    port: 12345
    shellID: 1
    has_chip_kick: false

  1:
    ip: "127.0.0.1"
    port: 50514
    shellID: 2
    has_chip_kick: false

  2:
    ip: "127.0.0.1"
    port: 50514
    shellID: 3
    has_chip_kick: false

  3:
    ip: "127.0.0.1"
    port: 50514
    shellID: 4 
    has_chip_kick: false

  4: 
    ip: "127.0.0.1"
    port: 50514
    shellID: 5
    has_chip_kick: false

  5:
    ip: "127.0.0.1"
    port: 50514
    shellID: 6
    has_chip_kick: false

